version: '3.5'
services:
  parsedmarc:
    #image: parsedmarc
    build: ./parsedmarc/
    volumes:
      - ./files:/input:ro
      - ./output-files:/output
      - ./parsedmarc.ini:/parsedmarc.ini
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data

  grafana:
    #image: grafana-parsedmarc
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
